### ISSUE TITLE
node-generator fails because npm registry is the default 

### ISSUE THREAD

**Issue by kfiven** [flatpak/flatpak-builder-tools#301]
When a package have different registry node generator fails to generate sources because it looks for that package in npm.

Example:
* https://github.com/cinnyapp/cinny/blob/dev/package-lock.json#L2407  
* Example run https://github.com/kfiven/cinny-desktop/runs/7216739597?check_suite_focus=true#step:10:3095

**Comment by catsout** [comment]
Why does the node-generator not use the resolved directly?

**Comment by gasinvein** [comment]
@catsout Because there is no `resolved` field on url-as-dependency items; instead, the package url is specified in the `version` field. And we need to somehow distinguish between normal versions and url-versions (see #145).
OP has linked the wrong package-lock entry; it's [this one](https://github.com/cinnyapp/cinny/blob/5c0eb20cb446f5027d91f334d0cf6a669011e41c/package-lock.json#L15706) that causes failure.
