### ISSUE TITLE
Maven/Gradle support

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak-builder-tools#37]
This could be used to [package Bisq](https://github.com/dmp1ce/flatpak-bisq/issues/1) and [jadx](https://github.com/skylot/jadx).

**Comment by Yajo** [comment]
Would help kmcaster too. See https://github.com/flathub/flathub/pull/2165#issuecomment-803082132.

**Comment by mbooth101** [comment]
I maintain the java extensions and have been thinking about it.

Current status: Apache Ant, Apache Maven, and Gradle are available for use in the openjdk extensions, but building stuff from source is quite complex due to the offline nature of flathub builds.

I have been working on some tooling to help, and will keep this ticket updated.

**Comment by hadess** [comment]
This script looks easy enough to modify for our needs: https://github.com/flatpak/flatpak-builder-tools/blob/master/dotnet/flatpak-dotnet-generator.py

**Comment by muelli** [comment]
this seems to be tackled here: https://github.com/flatpak/flatpak-builder-tools/pull/276

**Comment by wvengen** [comment]
For Maven, https://github.com/flatpak/flatpak-builder/issues/58#issuecomment-781508777 is probably useful to know about (and used by some existing apps on Flathub).

**Comment by hadess** [comment]
Latest push(es) fixed warnings related to the regex syntax:
```
/home/hadess/Projects/Flathub/org.ghidra_sre.Ghidra/_deps_build/./flatpak-gradle-generator.py:83: SyntaxWarning: invalid escape sequence '\/'
  r = re.compile('https:\/\/[\w/\-?=%.]+\.[\w/\-?=%.]+')
```
